### ISSUE TITLE
panic: interface conversion: interface {} is string, not int

### ISSUE THREAD

**Issue by ssst0n3** [ssst0n3/app-template#2]
```
$ ./hack/swaggo.sh 
+ GO111MODULE=on GOPROXY= go install github.com/swaggo/swag/cmd/swag@latest
+ readlink -f ./hack/swaggo.sh
+ dirname /home/st0n3/myproject/app-template/hack/swaggo.sh
+ dirname /home/st0n3/myproject/app-template/hack
+ cd /home/st0n3/myproject/app-template
+ cd cmd/app
+ swag init --parseDependency --parseInternal -o ../../docs
2022/12/09 23:07:18 Generate swagger docs....
2022/12/09 23:07:18 Generate general API Info, search dir:./
panic: interface conversion: interface {} is string, not int

goroutine 1 [running]:
github.com/swaggo/swag.(*PackageDefinitions).evaluateConstValue(0xc00c0c3db0, 0x7f68d1bdf108?, 0x90?, {0xa5b4c0?, 0xc00c12e5d0?}, {0xa59a60, 0xc00007d820}, 0xc01019f588?)
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/package.go:132 +0x113f
github.com/swaggo/swag.(*PackageDefinitions).evaluateConstValue(0xc00c0c3db0, 0xc00fc7f290?, 0xc00a50bf20?, {0xa5b4c0?, 0xc00c12e600?}, {0xa59a60, 0xc00007d820}, 0x1a?)
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/package.go:115 +0xd9
github.com/swaggo/swag.(*PackagesDefinitions).EvaluateConstValue(0xc01019f698?, 0xc00c0c3db0, 0xc009deeb00, 0x0)
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:282 +0x19d
github.com/swaggo/swag.(*PackagesDefinitions).evaluateAllConstVariables(...)
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:265
github.com/swaggo/swag.(*PackagesDefinitions).ParseTypes(0xc00007d820)
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:110 +0x254
github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0xc0001d6000, {0xc0001d0020?, 0x1?, 0x0?}, {0x987aa2?, 0x7?}, 0x64)
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/parser.go:375 +0x3bf
github.com/swaggo/swag/gen.(*Gen).Build(0xc00019d8f0, 0xc0001982a0)
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/gen/gen.go:182 +0x637
main.initAction(0xc0001c0a00?)
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/cmd/swag/main.go:158 +0x7bd
github.com/urfave/cli/v2.(*Command).Run(0xc00017cc60, 0xc0001ba380)
        /home/st0n3/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5dc
github.com/urfave/cli/v2.(*App).RunContext(0xc000173520, {0xa5c4d0?, 0xc00002c0b8}, {0xc0000241e0, 0x6, 0x6})
        /home/st0n3/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb7d
github.com/urfave/cli/v2.(*App).Run(...)
        /home/st0n3/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/st0n3/go/pkg/mod/github.com/swaggo/swag@v1.8.8/cmd/swag/main.go:229 +0x5c5
```

**Comment by ssst0n3** [comment]
https://github.com/swaggo/swag/issues/1392

use v1.8.7 instead of v1.8.8
